version: '3'
services:
  nginx-frontend:
    build:
        context: ./frontend/docker/nginx
    volumes:
      - ./frontend:/var/www/frontend
    ports:
      - "8000:8000"
  nodejs-frontend:
    build:
      context: ./frontend/docker/nodejs
    volumes:
      - ./frontend:/var/www/frontend
    environment:
      - npm_config_unsafe_perm=true
      #allow hot reload on docker volumes
      - CHOKIDAR_USEPOLLING=true
      #decrease CPU load
      - CHOKIDAR_INTERVAL=1000
    working_dir: /var/www/frontend
    tty: true
