version: '3'
services:
  nginx-main-service:
    build:
      context: .docker/nginx
    volumes:
      - ./:/var/www/main-service
      - .docker/nginx/logs:/var/log/nginx
    ports:
      - "5000:5000"
  nodejs-main-service:
    build:
      context: .docker/nodejs
    volumes:
      - ./:/var/www/main-service
    working_dir: /var/www/main-service
    tty: true
    ports:
      - "3000:3000"
    networks:
      # naming is matter to use it from another docker-container
      - common-service_default
      - main-service_default
  redis-main-service:
    build:
      context: .docker/redis
    ports:
      - "6379:6379"
networks:
  # ability to connect from another docker-compose
  common-service_default:
    external: true
  main-service_default:
    external: true
